[package]
name = "ircticker"
version = "0.1.0"
authors = ["Ben Moyer <ben.s.moyer@gmail.com>"]

[dependencies]
curl = "0.4.12"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
chrono = "0.4"
select = "0.4.2"
reqwest = "0.8.7"
regex = "1.0.2"
irc = "0.13.5"
